/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.fengshch.mybatis;

import com.github.fengshch.mybatis.config.DataSourceConfigBuilder;
import com.github.fengshch.mybatis.config.GlobalConfigBuilder;
import com.github.fengshch.mybatis.ext.MyBatisExtension;
import com.github.fengshch.mybatis.tasks.*;
import org.apache.commons.lang3.StringUtils;
import org.flywaydb.gradle.FlywayExtension;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.plugins.JavaBasePlugin;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import org.jetbrains.annotations.NotNull;
import org.yaml.snakeyaml.Yaml;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.*;

/**
 * Gradle plugin for MyBatis Flex code generation.
 *
 * This plugin provides automated code generation capabilities for MyBatis Flex, including
 * Entity, Mapper, Service, ServiceImpl, Controller, and TableDef classes. It integrates with
 * Flyway for database migration management and supports multiple independent configurations
 * through the {@link MyBatisExtension}.
 *
 * @see MyBatisExtension
 * @see GlobalConfigBuilder
 * @see MyBatisGenerateTask
 */
public class MyBatisFlexGradlePlugin implements Plugin<Project> {
    /**
     * Constructs a new {@code MyBatisFlexGradlePlugin}.
     */
    public MyBatisFlexGradlePlugin() {
    }

    public void apply(Project project) {
        project.getPlugins().apply(JavaBasePlugin.class);

        MyBatisExtension myBatisExtension = project.getExtensions().create("mybatis", MyBatisExtension.class);
        project.getExtensions().create("flyway", FlywayExtension.class);

        // Load configurations from mybatis-flex.yml if it exists
        loadConfigurationsFromYaml(project, myBatisExtension);

        project.afterEvaluate(p -> {
            System.out.println("mybatis: " + myBatisExtension.getConfigurations().getNames());
            myBatisExtension.getConfigurations().forEach(globalConfigBuilder -> {
                configDatasource(project, globalConfigBuilder);
                createGenerateTask(project, globalConfigBuilder);

                project.getPlugins().withType(JavaBasePlugin.class, javaBasePlugin -> {
                    JavaPluginExtension javaPluginExtension = project.getExtensions().getByType(JavaPluginExtension.class);
                    SourceSetContainer sourceSets = javaPluginExtension.getSourceSets();

                    if (sourceSets.getNames().contains("main")) {
                        SourceSet sourceSet = sourceSets.getByName(SourceSet.MAIN_SOURCE_SET_NAME);
                        String batisSourceSetJavaDir = globalConfigBuilder.getPackageConfigBuilder().getSourceDir();
                        if(batisSourceSetJavaDir != null && !batisSourceSetJavaDir.equals("src/main/java")) {
                            sourceSet.getJava().srcDir(batisSourceSetJavaDir);
                        }
                    }
                });

                FlywayExtension flywayExtension = globalConfigBuilder.getFlywayExtension();
                applyFlywayTask(project, globalConfigBuilder, flywayExtension);
            });
        });
    }

    private void createGenerateTask(Project project, GlobalConfigBuilder globalConfigBuilder) {
        String name = globalConfigBuilder.getName().equals("main") ? "" : globalConfigBuilder.getName();
        String taskName = "mybatis%sGenerate".formatted(StringUtils.capitalize(name));
        project.getTasks().register(taskName, MyBatisGenerateTask.class, globalConfigBuilder);
    }

    /**
     * Loads MyBatis Flex configurations from mybatis-flex.yml file if it exists.
     * This allows users to define configurations in YAML instead of build.gradle.
     *
     * @param project the Gradle project
     * @param myBatisExtension the MyBatis extension to populate with configurations
     */
    @SuppressWarnings("unchecked")
    private void loadConfigurationsFromYaml(Project project, MyBatisExtension myBatisExtension) {
        File flexConfigFile = project.file("src/main/resources/mybatis-flex.yml");
        if (!flexConfigFile.exists()) {
            return;
        }

        try (FileInputStream yamlStream = new FileInputStream(flexConfigFile)) {
            Yaml yaml = new Yaml();
            Map<String, Object> props = yaml.load(yamlStream);

            if (props == null) {
                return;
            }

            Map<String, Object> mybatisFlexConfig = (Map<String, Object>) props.get("mybatis-flex");
            if (mybatisFlexConfig == null) {
                return;
            }

            Map<String, Object> configurations = (Map<String, Object>) mybatisFlexConfig.get("configurations");
            if (configurations == null) {
                return;
            }

            // Process each configuration
            for (Map.Entry<String, Object> entry : configurations.entrySet()) {
                String configName = entry.getKey();
                Map<String, Object> configData = (Map<String, Object>) entry.getValue();

                GlobalConfigBuilder configBuilder = myBatisExtension.getConfigurations().create(configName);
                applyYamlConfiguration(configBuilder, configData);
            }
        } catch (Exception e) {
            project.getLogger().warn("Failed to load mybatis-flex.yml: " + e.getMessage());
        }
    }

    /**
     * Applies YAML configuration data to a GlobalConfigBuilder.
     *
     * @param configBuilder the configuration builder to populate
     * @param configData the YAML configuration data
     */
    @SuppressWarnings("unchecked")
    private void applyYamlConfiguration(GlobalConfigBuilder configBuilder, Map<String, Object> configData) {
        // Apply generation enable flags
        if (configData.containsKey("controllerGenerateEnable")) {
            configBuilder.setControllerGenerateEnable((Boolean) configData.get("controllerGenerateEnable"));
        }
        if (configData.containsKey("entityGenerateEnable")) {
            configBuilder.setEntityGenerateEnable((Boolean) configData.get("entityGenerateEnable"));
        }
        if (configData.containsKey("mapperGenerateEnable")) {
            configBuilder.setMapperGenerateEnable((Boolean) configData.get("mapperGenerateEnable"));
        }
        if (configData.containsKey("serviceGenerateEnable")) {
            configBuilder.setServiceGenerateEnable((Boolean) configData.get("serviceGenerateEnable"));
        }
        if (configData.containsKey("serviceImplGenerateEnable")) {
            configBuilder.setServiceImplGenerateEnable((Boolean) configData.get("serviceImplGenerateEnable"));
        }
        if (configData.containsKey("tableDefGenerateEnable")) {
            configBuilder.setTableDefGenerateEnable((Boolean) configData.get("tableDefGenerateEnable"));
        }
        if (configData.containsKey("mapperXmlGenerateEnable")) {
            configBuilder.setMapperXmlGenerateEnable((Boolean) configData.get("mapperXmlGenerateEnable"));
        }

        // Apply package configuration
        if (configData.containsKey("packageConfig")) {
            Map<String, Object> packageConfig = (Map<String, Object>) configData.get("packageConfig");
            if (packageConfig.containsKey("sourceDir")) {
                configBuilder.getPackageConfigBuilder().setSourceDir((String) packageConfig.get("sourceDir"));
            }
            if (packageConfig.containsKey("basePackage")) {
                configBuilder.getPackageConfigBuilder().setBasePackage((String) packageConfig.get("basePackage"));
            }
            if (packageConfig.containsKey("entityPackage")) {
                configBuilder.getPackageConfigBuilder().setEntityPackage((String) packageConfig.get("entityPackage"));
            }
            if (packageConfig.containsKey("mapperPackage")) {
                configBuilder.getPackageConfigBuilder().setMapperPackage((String) packageConfig.get("mapperPackage"));
            }
            if (packageConfig.containsKey("servicePackage")) {
                configBuilder.getPackageConfigBuilder().setServicePackage((String) packageConfig.get("servicePackage"));
            }
            if (packageConfig.containsKey("serviceImplPackage")) {
                configBuilder.getPackageConfigBuilder().setServiceImplPackage((String) packageConfig.get("serviceImplPackage"));
            }
            if (packageConfig.containsKey("controllerPackage")) {
                configBuilder.getPackageConfigBuilder().setControllerPackage((String) packageConfig.get("controllerPackage"));
            }
            if (packageConfig.containsKey("tableDefPackage")) {
                configBuilder.getPackageConfigBuilder().setTableDefPackage((String) packageConfig.get("tableDefPackage"));
            }
            if (packageConfig.containsKey("mapperXmlPath")) {
                configBuilder.getPackageConfigBuilder().setMapperXmlPath((String) packageConfig.get("mapperXmlPath"));
            }
        }

        // Apply strategy configuration
        if (configData.containsKey("strategyConfig")) {
            Map<String, Object> strategyConfig = (Map<String, Object>) configData.get("strategyConfig");
            if (strategyConfig.containsKey("tablePrefix")) {
                configBuilder.getStrategyConfigBuilder().setTablePrefix((String) strategyConfig.get("tablePrefix"));
            }
            if (strategyConfig.containsKey("logicDeleteColumn")) {
                configBuilder.getStrategyConfigBuilder().setLogicDeleteColumn((String) strategyConfig.get("logicDeleteColumn"));
            }
            if (strategyConfig.containsKey("versionColumn")) {
                configBuilder.getStrategyConfigBuilder().setVersionColumn((String) strategyConfig.get("versionColumn"));
            }
            if (strategyConfig.containsKey("generateForView")) {
                configBuilder.getStrategyConfigBuilder().setGenerateForView((Boolean) strategyConfig.get("generateForView"));
            }
            if (strategyConfig.containsKey("unGenerateTables")) {
                List<String> tables = (List<String>) strategyConfig.get("unGenerateTables");
                configBuilder.getStrategyConfigBuilder().setUnGenerateTables(tables.toArray(new String[0]));
            }
            if (strategyConfig.containsKey("generateSchema")) {
                configBuilder.getStrategyConfigBuilder().setGenerateSchema((String) strategyConfig.get("generateSchema"));
            }
        }

        // Apply Flyway configuration
        if (configData.containsKey("flyway")) {
            Map<String, Object> flywayConfig = (Map<String, Object>) configData.get("flyway");
            FlywayExtension flywayExtension = configBuilder.getFlywayExtension();

            if (flywayConfig.containsKey("cleanDisabled")) {
                flywayExtension.cleanDisabled = (Boolean) flywayConfig.get("cleanDisabled");
            }
            if (flywayConfig.containsKey("locations")) {
                Object locations = flywayConfig.get("locations");
                if (locations instanceof List) {
                    flywayExtension.locations = ((List<String>) locations).toArray(new String[0]);
                } else if (locations instanceof String) {
                    flywayExtension.locations = new String[]{(String) locations};
                }
            }
            if (flywayConfig.containsKey("baselineVersion")) {
                flywayExtension.baselineVersion = (String) flywayConfig.get("baselineVersion");
            }
            if (flywayConfig.containsKey("baselineDescription")) {
                flywayExtension.baselineDescription = (String) flywayConfig.get("baselineDescription");
            }
            if (flywayConfig.containsKey("table")) {
                flywayExtension.table = (String) flywayConfig.get("table");
            }
            if (flywayConfig.containsKey("schemas")) {
                Object schemas = flywayConfig.get("schemas");
                if (schemas instanceof List) {
                    flywayExtension.schemas = ((List<String>) schemas).toArray(new String[0]);
                } else if (schemas instanceof String) {
                    flywayExtension.schemas = new String[]{(String) schemas};
                }
            }
        }
    }


    @SuppressWarnings("unchecked")
    private void configDatasource(Project project, GlobalConfigBuilder globalConfigBuilder) {
        String profile = getProfile(project);
        DataSourceConfigBuilder dataSourceConfig = globalConfigBuilder.getDataSourceConfigBuilder();
        File configFile = getConfigFile(project, profile);

        Map<String, Object> datasource = readDataSourceConfig(configFile);
        datasource = configH2Datasource(datasource, project);
        setConfigFromMap(dataSourceConfig, "main".equals(globalConfigBuilder.getName()) ? Objects.requireNonNull(datasource) : (Map<String, Object>) Objects.requireNonNull(datasource).get(globalConfigBuilder.getName()));
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> readDataSourceConfig(File configFile) {
        try (FileInputStream yamlStream = new FileInputStream(configFile)) {
            Yaml yaml = new Yaml();
            Iterable<Object> documents = yaml.loadAll(yamlStream);
            for (Object document : documents) {
                Map<String, Object> props = (Map<String, Object>) document;
                if (props != null) {
                    Map<String, Object> spring = (Map<String, Object>) props.get("spring");
                    if (spring != null) {
                        Map<String, Object> datasource = (Map<String, Object>) spring.get("datasource");
                        if (datasource != null) {
                            return datasource;
                        }
                    }
                }
            }
        } catch (Exception e) {
            throw new RuntimeException("Failed to read YAML file", e);
        }
        return null;
    }

    private String getProfile(Project project) {
        if (project.hasProperty("profile")) return (String) project.property("profile");
        String activeProfile = getActiveProfile(project);
        if (activeProfile != null) return activeProfile;
        return System.getenv("PROFILE") != null ? System.getenv("PROFILE") : "default";
    }

    private File getConfigFile(Project project, String profile) {
        File flexConfigFile = project.file("src/main/resources/mybatis-flex.yml");
        if (flexConfigFile.exists()) return flexConfigFile;

        Map<String, String> pathsMap = getStringStringMap();
        return project.file(pathsMap.get(profile));
    }

    @NotNull
    private static Map<String, String> getStringStringMap() {
        Map<String, String> pathsMap = new HashMap<>();
        pathsMap.put("default", "src/main/resources/application.yml");
        pathsMap.put("dev", "src/main/resources/application-dev.yml");
        pathsMap.put("test", "src/main/resources/application-test.yml");
        return pathsMap;
    }

//    private Iterable<Object> loadYaml(File file) {
//        Yaml yaml = new Yaml();
//        try (FileInputStream fis = new FileInputStream(file)) {
//            return yaml.loadAll(fis);
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }
//    }

    private Properties loadProperties(File file) throws IOException {
        Properties properties = new Properties();
        try (FileInputStream fis = new FileInputStream(file)) {
            properties.load(fis);
        }
        return properties;
    }

    private void setConfigFromMap(DataSourceConfigBuilder config, Map<String, Object> datasource) {
        config.setDriverClassName(String.valueOf(datasource.getOrDefault("driverClassName", datasource.get("driver-class-name"))));
        config.setUrl(String.valueOf(datasource.get("url")));
        config.setUsername(String.valueOf(datasource.get("username")));
        config.setPassword(String.valueOf(datasource.get("password")));
    }

    private void setConfigFromProperties(DataSourceConfigBuilder config, Properties properties, String prefix) {
        config.setDriverClassName(properties.getProperty(prefix + ".driverClassName", properties.getProperty(prefix + ".driver-class-name")));
        config.setUrl(properties.getProperty(prefix + ".url"));
        config.setUsername(properties.getProperty(prefix + ".username"));
        config.setPassword(properties.getProperty(prefix + ".password"));
    }

    private void applyFlywayTask(Project project, GlobalConfigBuilder globalConfigBuilder, FlywayExtension
            flywayExtension) {
        String taskNamePri = globalConfigBuilder.getName().equals("main") ? "flyway" : globalConfigBuilder.getName();
        project.getTasks().register(taskNamePri + "Clean", CustomFlywayCleanTask.class, flywayExtension);
        project.getTasks().register(taskNamePri + "Baseline", CustomFlywayBaselineTask.class, flywayExtension);
        project.getTasks().register(taskNamePri + "Migrate", CustomFlywayMigrateTask.class, flywayExtension);
        project.getTasks().register(taskNamePri + "Undo", CustomFlywayUndoTask.class, flywayExtension);
        project.getTasks().register(taskNamePri + "Validate", CustomFlywayValidateTask.class, flywayExtension);
        project.getTasks().register(taskNamePri + "Info", CustomFlywayInfoTask.class, flywayExtension);
        project.getTasks().register(taskNamePri + "Repair", CustomFlywayRepairTask.class, flywayExtension);
    }

    @SuppressWarnings("unchecked")
    private String getActiveProfile(Project project) {
        File yamlFile = project.file("src/main/resources/application.yml");
        if (yamlFile.exists()) {
            try (FileInputStream fis = new FileInputStream(yamlFile)) {
                Yaml yaml = new Yaml();
                Iterable<Object> documents = yaml.loadAll(fis);
                for (Object document : documents) {
                    Map<String, Object> props = (Map<String, Object>) document;
                    if (props != null) {
                        Map<String, Object> spring = (Map<String, Object>) props.get("spring");
                        if (spring != null) {
                            Map<String, Object> profiles = (Map<String, Object>) spring.get("profiles");
                            if (profiles != null) {
                                return (String) profiles.get("active");
                            }
                        }
                    }
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

        }
        return null;
    }

    private Map<String, Object> configH2Datasource(Map<String, Object> datasource, Project project) {
        if (datasource == null)
            return null;
        String url = (String) datasource.get("url");
        if (url.contains("jdbc:h2:file:./")) {
            String path = project.getProjectDir().getAbsolutePath();
            url = url.replace("jdbc:h2:file:./", "jdbc:h2:file:" + path + "/");
        }
        if (url.contains("jdbc:h2:file:../")) {
            String path = project.getProjectDir().getParentFile().getAbsolutePath();
            url = url.replace("jdbc:h2:file:../", "jdbc:h2:file:" + path + "/");
        }
        datasource.put("url", url);
        return datasource;
    }
}
