spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.12.216:3306/ssia?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: bill
    password: 123456